#include"main.h"
void main()
{
int i;
 Set_Video_Mode(VGA256);
 // Blit_String(200,100,10,"game over",1);
	//   begin();

	 //  for(i=0;i<256;i++)
	  // {
	   //line(20+i,20,20+i,150,i);
	  // }

	// getch();
	test();
   //portfunc();
	 getch();
	// jiemian_manage_current();
	// getch();
	 //jiemian_manage_history();
	//fill_Rectangle(285,100,315,115,8);
	//fill_Rectangle(285,100,314,114,7);
	//fill_Rectangle(286,101,314,114,24);
	//mouse()
  //Set_Video_Mode(TEXT_MODE);

  
}
